title: "Malware Diaries"
description: "A blog dedicated to malware analysis and cybersecurity insights."
author: "Rinal"
theme: minima
markdown: kramdown

# Optional navigation links
header_pages:
  - index.md
  - zero2auto.md  # New section
  - insights.md   # New section
  - walkthroughs.md # New section
