title: "Malware Diaries"
description: "A blog dedicated to malware analysis and cybersecurity insights."
author: "Rinal"
theme: minima
markdown: kramdown

# Optional navigation links (can be customized later)
header_pages:
  - index.md
